### ISSUE TITLE
incorrect font

### ISSUE THREAD

**Issue by vanyakosmos** [Beafantles/picode#1]
“Bitstream Vera Sans Mono” should be for Windows, and Courier New for *nix
and in your lib they are reversed

**Comment by OldBeafantles** [comment]
Actually, I think this should be Courier new for Windows (as it is default installed since Windows 3.1) and Liberation Mono for Linux (because I don't think Bitstream Vera Sans Mono is pre-installed on all Linux systems). I will fix it as soon as I can! :)
